default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  encoding: unicode
  database: res_development
  pool: 5

test: &test
  adapter: sqlite3
  encoding: unicode
  database: res_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: bluebird_production
  host: localhost
  pool: 5
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>